[package]
name = "structdiff-nvim-tests"
version.workspace = true
edition.workspace = true
publish.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
nvim-oxi = { workspace = true, features = ["neovim-0-12", "libuv", "test"] }
structdiff = { workspace = true }
structdiff-core = { workspace = true }
structdiff-testutil = { workspace = true }
serde_json = "1"

[build-dependencies]
nvim-oxi = { workspace = true, features = ["neovim-0-12", "test"] }
